tests: disable GidsApplet
... because it cannot be instrumented properly:
```
spoon.compiler.ModelBuildingException: Config cannot be resolved to a variable at /Users/runner/work/JCProfilerNext/JCProfilerNext/tests/GidsApplet_ctor_0es07gtp/sources_original/TransmitManager.java:104
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.report(JDTBasedSpoonCompiler.java:649) ~[JCProfilerNext-1.0-SNAPSHOT.jar:?]
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.reportProblems(JDTBasedSpoonCompiler.java:631) ~[JCProfilerNext-1.0-SNAPSHOT.jar:?]
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.build(JDTBasedSpoonCompiler.java:118) ~[JCProfilerNext-1.0-SNAPSHOT.jar:?]
	at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.build(JDTBasedSpoonCompiler.java:99) ~[JCProfilerNext-1.0-SNAPSHOT.jar:?]
	at spoon.Launcher.buildModel(Launcher.java:781) ~[JCProfilerNext-1.0-SNAPSHOT.jar:?]
	at jcprofiler.instrumentation.Instrumenter.buildModel(Instrumenter.java:124) ~[JCProfilerNext-1.0-SNAPSHOT.jar:?]
	at jcprofiler.instrumentation.Instrumenter.addMissingClasses(Instrumenter.java:175) ~[JCProfilerNext-1.0-SNAPSHOT.jar:?]
	at jcprofiler.instrumentation.Instrumenter.process(Instrumenter.java:64) ~[JCProfilerNext-1.0-SNAPSHOT.jar:?]
	at jcprofiler.JCProfiler.run(JCProfiler.java:51) ~[JCProfilerNext-1.0-SNAPSHOT.jar:?]
	at jcprofiler.Main.main(Main.java:79) [JCProfilerNext-1.0-SNAPSHOT.jar:?]
```